# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI with Maven

on:
  push:
    branches:
      - feature-*
      - release-*
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Compilando o código fonte
      run: mvn clean compile
  test:
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: rodando os testes configurados
      run: mvn test
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
    - run: mvn --batch-mode --update-snapshots clean verify
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: criando-pipeline/target/criando-pipeline.war

  deploy-in-desenvolvimento:
    needs: [build]
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2 
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          java-version: '8'
          distribution: 'adopt'
          run:
            mkdir -p criando-pipeline/target
            mv criando-pipeline.war criando-pipeline/target
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "criando-pipeline" #Must be unique in Heroku
          heroku_email: "e.syadetbo@gmail.com"
