# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI with Maven

on:
  push:
    branches:
      - feature-*
      - release-*
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify

  deploy-in-desenvolvimento:
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: ambiente-desenvolvimento
      url: http://criandopipeline.com
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2 
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir desenvolvimento && cp target/*.war desenvolvimento
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: desenvolvimento
